#!/usr/bin/env node

var validate = require(__dirname+'/../index')

var files = [
__dirname+"/../examples/abox.json",
__dirname+"/../examples/app.json",
__dirname+"/../examples/arcold.json",
__dirname+"/../examples/asmallbox.json",
__dirname+"/../examples/asteroids.json",
__dirname+"/../examples/ball.json",
__dirname+"/../examples/BoxEm.json",
__dirname+"/../examples/browser.json",
__dirname+"/../examples/bub.json",
__dirname+"/../examples/bubble.json",
__dirname+"/../examples/bubbles.json",
__dirname+"/../examples/bubs.json",
__dirname+"/../examples/bubs2.json",
__dirname+"/../examples/bubs3.json",
__dirname+"/../examples/cube.json",
__dirname+"/../examples/extrusion.json",
__dirname+"/../examples/flower.json",
__dirname+"/../examples/flower3.json",
__dirname+"/../examples/flowerproto.json",
__dirname+"/../examples/flowers.json",
__dirname+"/../examples/flowers2.json",
__dirname+"/../examples/flowers4.json",
__dirname+"/../examples/flowers7.json",
__dirname+"/../examples/force.json",
__dirname+"/../examples/forcenode.json",
__dirname+"/../examples/fors.json",
__dirname+"/../examples/fors2.json",
__dirname+"/../examples/freewrlflowers.json",
__dirname+"/../examples/geo.json",
__dirname+"/../examples/geobubbles.json",
__dirname+"/../examples/glflowers.json",
__dirname+"/../examples/ifscube.json",
__dirname+"/../examples/ifscubeworks.json",
__dirname+"/../examples/john.json",
__dirname+"/../examples/john2.json",
__dirname+"/../examples/john3.json",
__dirname+"/../examples/mirror.json",
__dirname+"/../examples/mirror2.json",
__dirname+"/../examples/MyBounce.json",
__dirname+"/../examples/plainflowers.json",
__dirname+"/../examples/pp3.json",
__dirname+"/../examples/qq3.json",
__dirname+"/../examples/rubik.json",
__dirname+"/../examples/rubikFurnace.json",
__dirname+"/../examples/rubikOnFire.json",
__dirname+"/../examples/sphere.json",
__dirname+"/../examples/sphereflowers.json",
__dirname+"/../examples/text.json",
__dirname+"/../examples/x3domflowers.json" ];

validate(files);
